trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'todoapplists'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'todopull'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(imageName):$(tag)

- stage: Notify
  displayName: Notify
  jobs:
  - job: Notify
    displayName: Notify
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo "The Docker image has been built successfully."
        echo "To run the image locally, follow these steps:"
        echo "1. Ensure Docker is running on your desktop."
        echo "2. Pull the image from the Azure DevOps Pipeline: docker pull $(Build.SourcesDirectory)/$(imageName):$(tag)"
        echo "3. Run the container: docker run -d -p 8080:8080 $(imageName):$(tag)"
      displayName: Print instructions
