trigger:
- main

pool:
  name: 'todopull' 

variables:
  repositoryName: 'todolist-app' 

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'docker-service'
    repository: $(repositoryName)
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'