trigger:
- main

variables:
  dockerId: "kokoopoli"  # Case-sensitive
  imageRepository: "todolist-app"  # Must exist on Docker Hub
  tag: "$(Build.BuildId)"

stages:
- stage: BuildAndPush
  displayName: Build and Push
  jobs:
  - job: DockerJob
    pool: todopull  # Your self-hosted pool
    steps:
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: "dockerhub-service"  # Verified service connection

    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        repository: $(dockerId)/$(imageRepository)  # Correct format
        dockerfile: "Dockerfile"
        containerRegistry: "dockerhub-service"
        tags: |
          $(tag)
          latest  # Optional