trigger:
- main

variables:
  dockerId: 'kokoopoli'  # Replace with yours
  imageRepository: 'todolist-app'   # Replace with yours
  tag: '$(Build.BuildId)'
  dockerHost: 'tcp://localhost:2375'   # Windows Docker daemon endpoint

stages:
- stage: BuildAndRun
  displayName: Build and Run Container
  jobs:
  - job: DockerJob
    displayName: Docker Operations
    pool: todopull
    
    steps:
    # Cleanup existing containers (Windows compatible)
    - powershell: |
        docker rm -f myapp-container 2>&1 | Out-Null
        if ($LASTEXITCODE -ne 0) { Write-Host "No existing container found" }
      displayName: Cleanup Containers
      env:
        DOCKER_HOST: $(dockerHost)

    # Docker login task
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: 'dockerhub-service'

    # Build and push image
    - task: Docker@2
      displayName: Build and Push Image
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: 'Dockerfile'
        containerRegistry: 'dockerhub-service'
        tags: |
          $(tag)
          latest

    # Run container with Windows configuration
    - powershell: |
        docker run -d `
        --name myapp-container `
        -p 3000:3000 `
        --restart unless-stopped `
        $(dockerId)/$(imageRepository):$(tag)
        
        Start-Sleep -Seconds 5
        docker ps
        docker logs myapp-container
      displayName: Run and Verify Container
      env:
        DOCKER_HOST: $(dockerHost)