trigger:
- main

variables:
  dockerId: 'kokoopoli'
  imageRepository: 'todolist-app'
  tag: '$(Build.BuildId)'

stages:
- stage: BuildAndRun
  displayName: Docker Build/Push
  jobs:
  - job: DockerJob
    pool: todopull
    steps:
    - task: Docker@2
      displayName: Docker Login
      inputs:
        command: login
        containerRegistry: 'dockerhub-service'

    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        repository: $(dockerId)/$(imageRepository)
        dockerfile: 'Dockerfile'
        containerRegistry: 'dockerhub-service'
        tags: |
          $(tag)
          latest

    - powershell: |
        docker run -d `
        -p 3000:3000 `
        --name test-container `
        $(dockerId)/$(imageRepository):$(tag)
      displayName: Test Container