trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'todolistapplication'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
     name: 'todopull'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(imageName):$(tag)
    - task: Docker@2
      displayName: Save Docker image as artifact
      inputs:
        command: save
        image: '$(imageName):$(tag)'
        saveAs: '$(Build.ArtifactStagingDirectory)/$(imageName).tar'
    - publish: $(Build.ArtifactStagingDirectory)
      artifact: dockerImage

- stage: Notify
  displayName: Notify
  jobs:
  - job: Notify
    displayName: Notify
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo "The Docker image has been built and saved as an artifact."
        echo "Download the artifact and load it into your local Docker:"
        echo "1. Download the .tar file from Azure DevOps artifacts."
        echo "2. Load the image into Docker: docker load -i todolistapplication.tar"
      displayName: Print instructions
