trigger:
  - main

variables:
  imageName: 'todo-list-app'
  registry: 'arcpull121.azurecr.io'
  dockerfilePath: '**/Dockerfile'

stages:
  - stage: Build
    displayName: Build and Push
    jobs:
      - job: Build
        displayName: Build Docker Image
        pool:
          name: todopull  # Your self-hosted agent pool name
        steps:
          - checkout: self

          # Log in to the container registry (example for Azure Container Registry)
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: acr-service-connection  # Pre-configured Azure service connection for ACR

          # Build and push the Docker image
          - task: Docker@2
            displayName: Build and Push
            inputs:
              command: buildAndPush
              repository: $(imageName)
              Dockerfile: $(dockerfilePath)
              containerRegistry: $(registry)
              tags: |
                latest

  - stage: Deploy
    displayName: Deploy Container
    dependsOn: Build
    jobs:
      - job: Deploy
        displayName: Deploy to Docker
        pool:
          name: todopull  # Use your self-hosted agent pool
        steps:
          # Run the Docker container
          - script: |
              docker pull $(registry)/$(imageName):latest
              docker stop $(imageName) || true && docker rm $(imageName) || true
              docker run -d --name $(imageName) -p 8000:8000 $(registry)/$(imageName):latest
            displayName: Run Docker Container
