trigger:
- main  # Trigger on main branch changes

variables:
  dockerId: 'kokopoli'    # Replace with your Docker Hub ID
  imageRepository: 'todolist_app'     # Replace with your image name
  tag: '$(Build.BuildId)'               # Unique tag for each build

stages:
- stage: BuildAndRun
  displayName: Build and Run Container
  jobs:
  - job: DockerJob
    displayName: Docker Operations
    pool: todopull  # Using your self-hosted agent pool 🎯
    
    steps:
    # Cleanup any existing containers (optional)
    - script: |
        docker stop myapp-container || true
        docker rm myapp-container || true
      displayName: Cleanup Previous Containers

    # Authenticate with Docker Hub
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: 'dockerhub-service'

    # Build and Push Docker Image
    - task: Docker@2
      displayName: Build and Push Image
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: 'Dockerfile'  # Path to your Dockerfile
        containerRegistry: 'dockerhub-service'
        tags: |
          $(tag)
          latest

    # Run the Container
    - script: |
        docker run -d \
        --name myapp-container \
        -p 3000:3000 \
        $(dockerId)/$(imageRepository):$(tag)
        
        # Verify container status
        docker ps | grep myapp-container
        docker logs myapp-container
      displayName: Run and Verify Container